### PR TITLE
Change the new free game check mode

### PR DESCRIPTION
**Pull request by Papela**
Now it automatically checks for new games every 2 hours without having to open new tabs. Also at 16:05 (UTC), the time when free games usually come out on Epic Games, a new check is done again.

_I haven't done many tests and it would be good to check that everything works correctly._

### CODE REVIEW

**Comment by jbarcossc** [comment]
@Papela the setTimeout doesn't seem to work. I tested with every 5 seconds and it doesn't execute the checkAndUpdateGames function

**Comment by Papela** [comment]
Oh it's true. I'll try to fix it when I have time using _chrome.alarms_

**Comment by jbarcossc** [comment]
Ok! Let me know if you implement that! I like the improvement idea

**Comment by Papela** [comment]
I have tested using _chrome.alarms_ and it seems to work correctly executing calls every 2 hours.
But I have removed the alarm at 16:05 UTC since I still haven't gotten it to work correctly.
I will try to implement it in a future pull request

**Comment by Papela** [comment]
Anything new?

**Comment by jbarcossc** [comment]
Looks really good! It worked properly on my tests. Only thing, I changed from 2 hours to 1 hour

**Pull request merged**
